// Class automatically generated by Dev-C++ New Class wizard

#ifndef CARDGAME_H
#define CARDGAME_H

// No description
class Cardgame
{
      int players;
      static int totalParticipants;
	public:
		// class constructor
		Cardgame(int players);
		// class destructor
		~Cardgame();
		static int GetParticipants() {return totalParticipants; }
};

#endif // CARDGAME_H
